/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.assignment1;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Then Wei Cheng
 */
public class ApproveOrReject extends javax.swing.JFrame {
        private User user;
    /**
     * Creates new form ApproveOrReject
     */
    public ApproveOrReject(User user) {
        this.user = user;
        initComponents();
        loadAppointmentsFromFile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        approveBtn = new javax.swing.JButton();
        rejectBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jLabel1.setText("Approve Or Reject");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        // Add TableRowSorter for sorting functionality
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        javax.swing.table.TableRowSorter<DefaultTableModel> sorter = new javax.swing.table.TableRowSorter<>(model);
        jTable1.setRowSorter(sorter);
        jScrollPane1.setViewportView(jTable1);

        approveBtn.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        approveBtn.setText("Approve");
        approveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveBtnActionPerformed(evt);
            }
        });

        rejectBtn.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        rejectBtn.setText("Reject");
        rejectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Notes:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select" ,"Physical", "Online" }));

        backButton.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(249, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addGap(173, 173, 173)
                        .addComponent(rejectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(209, 209, 209)
                        .addComponent(approveBtn)
                        .addGap(418, 418, 418))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(585, 585, 585))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(approveBtn)
                    .addComponent(rejectBtn)
                    .addComponent(backButton))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadAppointmentsFromFile() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Clear the table before loading new data
        String[] colHeadings = {"AppointmentID","StudentsID","Username","SlotsID", "LectureID", "Username","TimeSlots", "Date", "Booked On", "Status", "Notes"};
        model.setColumnIdentifiers(colHeadings); // Set column headers

        try (BufferedReader br = new BufferedReader(new FileReader("appointment.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] row = line.split(",");
                if (row[4].trim().equals(user.getUserID().trim())) { // Check if appointment belongs to the student
                    if (row.length == 15 ) { 
                        model.addRow(row);
                    }
                }
            }
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File not found: appointment.txt", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error reading file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void approveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveBtnActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select an appointment to approve.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Get Appointment ID
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String appointmentID = (String) model.getValueAt(selectedRow, 0);
        String slotID = (String) model.getValueAt(selectedRow, 3);

        // Get selected meeting mode from ComboBox
        String meetingMode = (String) jComboBox1.getSelectedItem();
        if (meetingMode.equals("Please Select")) {
            JOptionPane.showMessageDialog(this, "Please select a meeting mode (Physical or Online).", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Update appointment.txt
        try (BufferedReader br = new BufferedReader(new FileReader("appointment.txt"))) {
            java.util.List<String> lines = new java.util.ArrayList<>();
            String line;
            while ((line = br.readLine()) != null) {
                if (line.startsWith(appointmentID + ",")) {
                    // Modify the line to set Status to Approved
                    String[] columns = line.split(",");
                    columns[9] = "Approved"; // Assuming Status is the 8th column (index 7)
                    columns[10] = meetingMode; // Assuming Notes/Mode is the 9th column (index 8)
                    line = String.join(",", columns);
                }
                lines.add(line);
            }
            java.nio.file.Files.write(java.nio.file.Paths.get("appointment.txt"), lines);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error updating appointment: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
              
        // Update Table Row
        model.setValueAt("Approved", selectedRow, 9); // Update Status column in the table
        model.setValueAt(meetingMode, selectedRow, 10); // Update Notes/Mode column in the table
        JOptionPane.showMessageDialog(this, "Appointment approved successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_approveBtnActionPerformed

    private void rejectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectBtnActionPerformed
        int selectedRow = jTable1.getSelectedRow();
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(this, "Please select an appointment to reject.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Get Appointment ID
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            String appointmentID = (String) model.getValueAt(selectedRow, 0);
            String slotID = (String) model.getValueAt(selectedRow, 3); // Assuming Slot ID is in column 3

            // Update appointment.txt (to set status to rejected)
            try (BufferedReader br = new BufferedReader(new FileReader("appointment.txt"))) {
                java.util.List<String> lines = new java.util.ArrayList<>();
                String line;
                while ((line = br.readLine()) != null) {
                    if (line.startsWith(appointmentID + ",")) {
                        // Modify the line to set Status to Rejected
                        String[] columns = line.split(",");
                        if (columns.length >= 10) { // Ensure valid format
                            columns[9] = "Rejected"; // Assuming Status is the 9th column (index 9)
                            line = String.join(",", columns);
                        }
                    }
                    lines.add(line);
                }
                java.nio.file.Files.write(java.nio.file.Paths.get("appointment.txt"), lines);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error updating appointment: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Update Table Row in GUI to reflect status change
            model.setValueAt("Rejected", selectedRow, 9); // Update Status column in the table
            JOptionPane.showMessageDialog(this, "Appointment rejected successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
//        int selectedRow = jTable1.getSelectedRow();
//        if (selectedRow == -1) {
//            JOptionPane.showMessageDialog(this, "Please select an appointment to reject.", "Error", JOptionPane.ERROR_MESSAGE);
//            return;
//        }
//
//        // Get Appointment ID
//        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
//        String appointmentID = (String) model.getValueAt(selectedRow, 0);
//        String slotID = (String) model.getValueAt(selectedRow, 2); // Assuming Slot ID is in column 2
//
//        // Update appointment.txt
//        try (BufferedReader br = new BufferedReader(new FileReader("appointment.txt"))) {
//            java.util.List<String> lines = new java.util.ArrayList<>();
//            String line;
//            while ((line = br.readLine()) != null) {
//                if (line.startsWith(appointmentID + ",")) {
//                    // Modify the line to set Status to Rejected
//                    String[] columns = line.split(",");
//                    if (columns.length >= 10) { // Ensure valid format
//                        columns[9] = "Rejected"; // Assuming Status is the 8th column (index 7)
//                        line = String.join(",", columns);
//                    }
//                }
//                lines.add(line);
//            }
//            java.nio.file.Files.write(java.nio.file.Paths.get("appointment.txt"), lines);
//        } catch (IOException e) {
//            JOptionPane.showMessageDialog(this, "Error updating appointment: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//            return;
//        }

//        // Step 2: Update slots.txt to clear the `userid` for the rejected slot
//        try (BufferedReader br = new BufferedReader(new FileReader("slots.txt"))) {
//            java.util.List<String> lines = new java.util.ArrayList<>();
//            String line;
//            while ((line = br.readLine()) != null) {
//                String[] row = line.split(",");
//                if (row.length > 1 && row[0].equals(slotID)) { // Match Slot ID
//                    row[1] = ""; // Clear the `userid` field to make it available
//                    line = String.join(",", row); // Rebuild the line
//                }
//                lines.add(line);
//            }
//            java.nio.file.Files.write(java.nio.file.Paths.get("slots.txt"), lines);
//        } catch (IOException e) {
//            JOptionPane.showMessageDialog(this, "Error updating slots: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//            return;
//        }
//        
//        // Update Table Row
//        model.setValueAt("Rejected", selectedRow, 9); // Update Status column in the table
//        JOptionPane.showMessageDialog(this, "Appointment rejected successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_rejectBtnActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        Lecturer_features Lf = new Lecturer_features(user);
        Lf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApproveOrReject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApproveOrReject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApproveOrReject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApproveOrReject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                User user = new User(null, null, null, null, null);
                new ApproveOrReject(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveBtn;
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton rejectBtn;
    // End of variables declaration//GEN-END:variables
}
