/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.assignment1;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Then Wei Cheng
 */
public class BookConsultation extends javax.swing.JFrame {
    private User user;

    /**
     * Creates new form MakeConsultation
     */
    public BookConsultation(User user) {
        this.user = user;
        initComponents();
        loadDataFromFile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        BookConsultationBtn = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        SearchBtn = new javax.swing.JButton();
        resetButtton = new javax.swing.JButton();
        Datelabel = new javax.swing.JLabel();
        Datetextfield = new javax.swing.JTextField();
        BackBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jLabel1.setText("APU PSYCHOLOGY CONSULTATION");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {}
        ){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        });
        jScrollPane1.setViewportView(jTable3);

        BookConsultationBtn.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        BookConsultationBtn.setText("Book Consultation");
        BookConsultationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookConsultationBtnActionPerformed(evt);
            }
        });

        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Search Lecturer ID:");

        SearchBtn.setText("Search");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        resetButtton.setText("Reset");
        resetButtton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButttonActionPerformed(evt);
            }
        });

        Datelabel.setText("Date:");

        Datetextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatetextfieldActionPerformed(evt);
            }
        });

        BackBtn.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147)
                        .addComponent(BookConsultationBtn)
                        .addGap(305, 305, 305))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 943, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Datelabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Datetextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SearchBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resetButtton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel2)))
                        .addGap(7, 7, 7))))
            .addGroup(layout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SearchBtn)
                            .addComponent(resetButtton))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Datelabel)
                            .addComponent(Datetextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BookConsultationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Method to check if a slot is already booked
    private boolean isSlotBooked(String slotID, String date, String timeSlot) {
        try (BufferedReader br = new BufferedReader(new FileReader("appointment.txt"))) {
            String line;
            DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss"); // Updated format
            while ((line = br.readLine()) != null) {
                String[] row = line.split(",");
                try {
                    LocalDateTime bookingTimestamp = LocalDateTime.parse(row[8], dateTimeFormatter);
                    Appointment appointment = new Appointment(
                        row[0], // appointmentID
                        new User(row[1], row[2], null, null, null), // student
                        new User(row[4], row[5], null, null, null), // lecturer
                        new Consultation(row[3], null, row[6]), // consultation
                        row[7], // bookingDate
                        bookingTimestamp, // bookingTimestamp
                        row[9], // status
                        row[10], // notes
                        row[11], // studentFeedback
                        row[12], // studentRating
                        row[13], // lecturerFeedback
                        row[14] // lecturerRating
                    );

                    // Check if the slot is booked
                    if (appointment.getConsultation().getSlotID().equals(slotID) &&
                        appointment.getBookingDate().equals(date) &&
                        appointment.getConsultation().getTimeSlot().equals(timeSlot) &&
                        !appointment.getStatus().equalsIgnoreCase("Rejected")) {
                        return true; // Slot is already booked
                    }
                } catch (DateTimeParseException e) {
                    JOptionPane.showMessageDialog(this, "Error parsing date-time: " + row[8], "Error", JOptionPane.ERROR_MESSAGE);
                    continue; // Skip this entry
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error checking slot availability: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        return false; // Slot is available
    }
    private void BookConsultationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookConsultationBtnActionPerformed
         int selectedRow = jTable3.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a row to book the consultation", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Retrieve slot details from the selected row
    String slotID = (String) jTable3.getValueAt(selectedRow, 0);
    String inputDate = Datetextfield.getText().trim();
    String selectedTimeSlot = (String) jTable3.getValueAt(selectedRow, 3);
    
    // Validate the booking date
    DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("h:mma");
    LocalDate parsedDate;

    try {
        // Parse the input date
        parsedDate = LocalDate.parse(inputDate, dateFormatter);

        // Check if the selected date is in the past
        if (parsedDate.isBefore(LocalDate.now())) {
            JOptionPane.showMessageDialog(this, "The selected date is in the past. Please choose a future date.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // If the booking is for today, validate the time slot
        if (parsedDate.isEqual(LocalDate.now())) {
            // Assume the time slot is provided separately
            String endTimeString = selectedTimeSlot; // Example; replace with actual input
            LocalTime endTime = LocalTime.parse(endTimeString, timeFormatter);

            // Compare the end time with the current time
            if (LocalTime.now().isAfter(endTime)) {
                JOptionPane.showMessageDialog(this, "This time slot has already passed. Please select a valid time.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
    } catch (DateTimeParseException e) {
        JOptionPane.showMessageDialog(this, "Invalid date format! Please use dd/MM/yyyy.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }



    // Check if the slot is already booked
    if (isSlotBooked(slotID, inputDate, selectedTimeSlot)) {
        JOptionPane.showMessageDialog(this, "This slot is already booked by another student. Please choose a different slot.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Confirm the booking
    int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to book this slot for " + inputDate + "?", "Confirm Booking", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        saveBookedDataToFile(); // Save updated data back to the file
        saveDataToAppointmentFile(selectedRow, inputDate); // Save appointment details
    }
    }//GEN-LAST:event_BookConsultationBtnActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        
        //clear table
        model.setRowCount(0);
        
        //reload the data from file and filter by lecture id
        try (BufferedReader br = new BufferedReader(new FileReader("slots.txt"))){
            String line;
            while ((line = br.readLine()) != null){ 
                String [] row = line.split(",");
                if (searchField.getText().trim().equals("") || row[1].equalsIgnoreCase(searchField.getText().trim())){ //match lecturer id
                    model.addRow(row);
                }
            }
        } catch (IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error loading data: " + e.getMessage(),"Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        Student_features Sf = new Student_features(user);
        Sf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void DatetextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatetextfieldActionPerformed
        String inputDate = Datetextfield.getText();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        
         try {
            // Parse and validate the date
            LocalDate parsedDate = LocalDate.parse(inputDate, formatter);

            // Ensure the date is not in the past
            if (parsedDate.isBefore(LocalDate.now())|| parsedDate.isEqual(LocalDate.now())) {
                JOptionPane.showMessageDialog(this, "The selected date is in the past. Please choose a future date.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Success message for valid date
            JOptionPane.showMessageDialog(this, "Valid date: " + parsedDate, "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Invalid date format! Use dd-MM-yyyy.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_DatetextfieldActionPerformed

    private void resetButttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButttonActionPerformed
        searchField.setText("");
    }//GEN-LAST:event_resetButttonActionPerformed
    private void saveBookedDataToFile(){
        File file = new File("slots.txt");
        List<String> allSlots = new ArrayList<>();

        // Step 1: Load all slots from the file
        if (file.exists()) {
            try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    allSlots.add(line);
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error reading slots file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        // Step 2: Update the relevant slot
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            String slotID = (String) model.getValueAt(i, 0); // Slot ID
            String updatedSlot = ""; // Construct the updated slot line

            for (int j = 0; j < model.getColumnCount(); j++) {
                updatedSlot += model.getValueAt(i, j);
                if (j < model.getColumnCount() - 1) {
                    updatedSlot += ","; // Add comma between values
                }
            }

            // Replace the corresponding slot in allSlots
            for (int k = 0; k < allSlots.size(); k++) {
                if (allSlots.get(k).startsWith(slotID + ",")) {
                    allSlots.set(k, updatedSlot); // Update the line for the specific slot
                    break;
                }
            }
        }

        // Step 3: Save all slots back to the file
        try (PrintWriter writer = new PrintWriter(new FileWriter(file))) {
            for (String slot : allSlots) {
                writer.println(slot);
            }
            JOptionPane.showMessageDialog(this, "Consultation slot booked successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error saving slots: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
}
    private void saveDataToAppointmentFile(int selectedRow, String bookingDate) {
        // Check if the appointment file exists, create it if not
        File appointmentFile = new File("appointment.txt");
        if (!appointmentFile.exists()) {
            try {
                appointmentFile.createNewFile();  // Create the file if it doesn't exist
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error creating appointment file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                return; // Exit method if file creation fails
            }
        }
        
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();

        // Retrieve data from the selected row
        String slotsID = (String) model.getValueAt(selectedRow, 0); // Slot ID
        String lecturerID = (String) model.getValueAt(selectedRow, 1); // Lecturer ID
        String lecturerName = (String) model.getValueAt(selectedRow, 2); // Lecturer Name
        String timeSlots = (String) model.getValueAt(selectedRow, 3); // Time Slot

        // Create User objects for student and lecturer
        User student = user; // Current logged-in user
        User lecturer = new User(lecturerID, lecturerName, null, null, null); // Lecturer

        // Create Consultation object
        Consultation consultation = new Consultation(slotsID, null,timeSlots);

        // Generate a unique Appointment ID and timestamp
        String appointmentID = "A" + (System.currentTimeMillis() / 1000);
        LocalDateTime bookingTimestamp = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        String formattedTimestamp = bookingTimestamp.format(formatter);

        // Create an Appointment object
        Appointment appointment = new Appointment(
            appointmentID, 
            student, 
            lecturer, 
            consultation, 
            bookingDate, 
            bookingTimestamp, 
            "Pending", 
            "Pending", 
            "None", 
            "None",
            "None", 
            "None"
        );

        // Save appointment details into the file
        try (java.io.PrintWriter writer = new java.io.PrintWriter(new java.io.FileWriter("appointment.txt", true))) {
            writer.println(String.join(",", appointment.toArray())); // Write appointment data
            JOptionPane.showMessageDialog(this, "Appointment saved successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error saving appointment: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
}

    private void loadDataFromFile() {
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        String[] colHeadings = {"SlotsID", "LectureID", "Name", "TimeSlots"};
        model.setColumnIdentifiers(colHeadings); // Set column headers

        try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader("slots.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] row = line.split(","); // Split each line by commas
                // Filter by StudentID
                //if (row[1].equals(userid)) {
                    //model.addRow(row); // Add only rows that match the logged-in lecturer
                //}
                if (row.length == colHeadings.length) {
                    model.addRow(row);
                }
            }
        } catch (IOException e) {
            // Handle case where file doesn't exist or other I/O errors
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Error loading data: " + e.getMessage(), 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookConsultation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookConsultation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookConsultation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookConsultation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run() {
                User user = new User(null, null, null, null, null);
                new BookConsultation(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton BookConsultationBtn;
    private javax.swing.JLabel Datelabel;
    private javax.swing.JTextField Datetextfield;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable3;
    private javax.swing.JButton resetButtton;
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables
}
