/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.assignment1;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Then Wei Cheng
 */
public class ConsultationManagement extends javax.swing.JFrame {
    private User user;
    private List<Consultation> consultations;

    
    /**
     * Creates new form ConsultationManagement
     */
    public ConsultationManagement(User user) {
        this.user = user;
        this.consultations = new ArrayList<>();
        initComponents();
        loadDataFromFile();
        loadDefaultTimeSlots();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        TimeSlots = new javax.swing.JTextField();
        SaveBtn = new javax.swing.JButton();
        ModifyBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String[] {}
        ){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        });
        jScrollPane1.setViewportView(jTable);

        jLabel3.setFont(new java.awt.Font("Serif", 2, 14)); // NOI18N
        jLabel3.setText("Time Slots:");

        TimeSlots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeSlotsActionPerformed(evt);
            }
        });

        SaveBtn.setFont(new java.awt.Font("Serif", 2, 14)); // NOI18N
        SaveBtn.setText("Add");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        ModifyBtn.setFont(new java.awt.Font("Serif", 2, 14)); // NOI18N
        ModifyBtn.setText("Modify");
        ModifyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyBtnActionPerformed(evt);
            }
        });

        UpdateBtn.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        UpdateBtn.setText("Update");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        DeleteBtn.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        DeleteBtn.setText("Delete");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        BackBtn.setFont(new java.awt.Font("Serif", 2, 14)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(TimeSlots, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SaveBtn)
                                    .addComponent(UpdateBtn))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ModifyBtn)
                                    .addComponent(DeleteBtn))
                                .addGap(35, 35, 35))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BackBtn)
                        .addGap(86, 86, 86))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TimeSlots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SaveBtn)
                            .addComponent(ModifyBtn))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UpdateBtn)
                            .addComponent(DeleteBtn))
                        .addGap(18, 18, 18)
                        .addComponent(BackBtn)))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModifyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
    int selectedRow = jTable.getSelectedRow();

    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a row to modify.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Get the selected consultation's user ID and check if it belongs to the current user
    String lectureID = (String) model.getValueAt(selectedRow, 1);  // Column 1: Lecture ID
    String currentUserID = user.getUserID();  // Get the current user ID

    if (!lectureID.equals(currentUserID)) {
        javax.swing.JOptionPane.showMessageDialog(this, "You can only modify your own consultations.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Populate the input fields with the selected row's data
    String timeSlot = model.getValueAt(selectedRow, 3).toString();  // Column 3: Time Slot
    TimeSlots.setText(timeSlot);
    }//GEN-LAST:event_ModifyBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        String timeSlot = TimeSlots.getText().trim();

        if (timeSlot.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all fields.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String uniqueSlotID = generateUniqueSlotID();  // Generate unique slot ID
        Consultation newConsultation = new Consultation(uniqueSlotID, user, timeSlot);  // Create a new consultation

        // Add the new consultation to the list
        consultations.add(newConsultation);

        // Update the table with the new consultation
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        model.addRow(newConsultation.toArray());

        // Clear input fields
        TimeSlots.setText("");

        // Save the updated consultations to the file (only for the current user)
        consultationFile();  // This method writes the current user's consultations to the file

        // Show success message
        javax.swing.JOptionPane.showMessageDialog(this, "Record added successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void TimeSlotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeSlotsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimeSlotsActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        int selectedRow = jTable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row to update.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String timeSlot = TimeSlots.getText().trim();

        if (timeSlot.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all fields before updating.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Get the selected consultation object
        Consultation selectedConsultation = consultations.get(selectedRow);
        selectedConsultation.setTimeSlot(timeSlot);

        // Update the table's displayed value
        model.setValueAt(timeSlot, selectedRow, 3); // 3 corresponds to the time slot column

        // Clear the time slot input field
        TimeSlots.setText("");

        // Save the updated consultations to file, ensuring only the current user's data is modified
        consultationFile();

        // Show success message
        javax.swing.JOptionPane.showMessageDialog(this, "Row updated successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void loadDataFromFile() {
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        String[] colHeadings = {"SlotsID", "LectureID", "Name", "TimeSlots"};
        model.setColumnIdentifiers(colHeadings); // Update column headers

        try (BufferedReader br = new BufferedReader(new FileReader("slots.txt"))) {
            String line;
            boolean fileHasData = false; // To check if the file already has data

            while ((line = br.readLine()) != null) {
                fileHasData = true;
                String[] row = line.split(",");

                // Ensure the row is valid (has at least 4 elements) and check if the UserID matches
                if (row.length >= 4) {
                    String slotID = row[0];
                    String userID = row[1]; // Assuming userID is in the 2nd position
                    String name = row[2];
                    String timeSlot = row[3];

                    // Check if the current row belongs to the logged-in user
                    if (userID.equals(user.getUserID())) {
                        // Add consultation to the list and table for this user
                        Consultation consultation = new Consultation(slotID, user, timeSlot);
                        consultations.add(consultation);
                        model.addRow(consultation.toArray()); // Add consultation to table
                    }
                }
            }

            // If no consultations were loaded from the file, load default time slots
            if (!fileHasData || consultations.isEmpty()) {
                loadDefaultTimeSlots();
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, 
                "File not found or error reading file. Default slots will be loaded.", 
                "Notice", 
                JOptionPane.INFORMATION_MESSAGE);
            loadDefaultTimeSlots(); // Fallback to default slots if file read fails
        }
    }

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        int selectedRow = jTable.getSelectedRow();

        // Check if a row is selected
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Confirm deletion
        int response = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to delete the selected row?", 
            "Confirm Delete", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            try {
                // Get the consultation data from the selected row
                String lectureID = (String) model.getValueAt(selectedRow, 1); // Column 1: Lecture ID
                String timeSlot = (String) model.getValueAt(selectedRow, 3);  // Column 3: Time Slot
                String userID = user.getUserID();  // Get the user ID

                // Find and remove the consultation for the current user
                Consultation selectedConsultation = consultations.get(selectedRow);
                if (selectedConsultation.getLectureID().equals(userID)) {
                    consultations.remove(selectedRow);
                    model.removeRow(selectedRow);

                    // Rewrite the slots file to exclude the deleted consultation
                    consultationFile();  // This method ensures only the current user's data is updated

                    JOptionPane.showMessageDialog(this, "Consultation deleted successfully.", 
                        "Success", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "You cannot delete a consultation that doesn't belong to you.", 
                        "Error", JOptionPane.ERROR_MESSAGE);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, 
                    "Error deleting consultation: " + e.getMessage(), 
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        Lecturer_features Lf = new Lecturer_features(user);
        Lf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void loadDefaultTimeSlots() {
        // Only load default time slots if the consultations list is empty
        if (consultations.isEmpty()) {
            String[] timeSlots = {
                "9am-9.30am", "9.30am-10am", "10am-10.30pm", "10.30pm-11pm",
                "11pm-11.30pm", "11.30pm-12pm", "12pm-12.30pm", "12.30pm-1pm", "1pm-1.30pm",
                "1.30pm-2pm", "2pm-2.30pm", "2.30pm-3pm", "3pm-3.30pm", "3.30pm-4pm", 
                "4pm-4.30pm", "4.30pm-5pm", "5pm-5.30pm", "5.30pm-6pm"
            };

            // Loop to add default time slots to the table and the consultations list
            for (String timeSlot : timeSlots) {
                boolean alreadyExists = false;
                for (Consultation existingConsultation : consultations) {
                    if (existingConsultation.getTimeSlot().equals(timeSlot)) {
                        alreadyExists = true;
                        break;
                    }
                }

                // Only add the time slot if it doesn't already exist in the list
                if (!alreadyExists) {
                    String uniqueSlotID = generateUniqueSlotID();
                    Consultation consultation = new Consultation(uniqueSlotID, user, timeSlot);
                    consultations.add(consultation);
                    DefaultTableModel model = (DefaultTableModel) jTable.getModel();
                    model.addRow(consultation.toArray());
                }
            }
            // Save these slots to the file
            consultationFile();
        }
    }
    
    // Method to generate a unique Slot ID
    private String generateUniqueSlotID() {
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        int maxSlotID = 0;

        // Iterate over the rows in the table to find the highest ID for the current lecturer
        for (int i = 0; i < model.getRowCount(); i++) {
            String slotID = model.getValueAt(i, 0).toString();
            if (slotID.startsWith("SLT_" + user.getUserID() + "_")) { // Only consider IDs belonging to the current lecturer
                try {
                    int currentID = Integer.parseInt(slotID.substring(("SLT_" + user.getUserID() + "_").length()));
                    maxSlotID = Math.max(maxSlotID, currentID); // Update max ID
                } catch (NumberFormatException e) {
                    // Ignore invalid Slot IDs
                }
            }
        }

        // Generate the next unique ID
        return "SLT_" + user.getUserID() + "_" +(maxSlotID + 1); // Include userid for uniqueness
    }
    private void consultationFile() {
        // Step 1: Read existing file data into memory
        List<String> allLines = new ArrayList<>();
        try (BufferedReader br = new BufferedReader(new FileReader("slots.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                allLines.add(line);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error reading data from file: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            return; // If we can't read the file, return without making any changes
        }

        // Step 2: Remove the current user's lines from the list
        List<String> updatedLines = new ArrayList<>();
        for (String line : allLines) {
            String[] row = line.split(",");
            if (row.length >= 2 && !row[1].equals(user.getUserID())) {
                updatedLines.add(line); // Keep only lines not belonging to the current user
            }
        }

        // Step 3: Write the updated data back to the file
        try (BufferedWriter bw = new BufferedWriter(new FileWriter("slots.txt"))) {
            // Write all remaining lines (including non-user data)
            for (String updatedLine : updatedLines) {
                bw.write(updatedLine);
                bw.newLine();
            }

            // Step 4: Add the current user's consultations back to the file
            for (Consultation consultation : consultations) {
                if (consultation.getLectureID().equals(user.getUserID())) {
                    String row = String.join(",", consultation.getSlotID(), consultation.getLectureID(), consultation.getName(),
                            consultation.getTimeSlot());
                    bw.write(row);
                    bw.newLine();
                }
            }

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error saving data to file: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
private void rewriteSlotsFile() {
    File file = new File("slots.txt");

    // Check if the file exists, and if not, create it
    try {
        if (!file.exists()) {
            file.createNewFile();
        }

        try (BufferedWriter bw = new BufferedWriter(new FileWriter(file))) {
            // Loop through all the consultations and write each one to the file
            for (Consultation consultation : consultations) {
                String row = String.join(",", consultation.getSlotID(), consultation.getLectureID(),
                                         consultation.getName(), consultation.getTimeSlot());
                bw.write(row);
                bw.newLine();
            }

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error saving data to file: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error creating file: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultationManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultationManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultationManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultationManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                User user = new User(null, null, null, null, null);
                new ConsultationManagement(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton ModifyBtn;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JTextField TimeSlots;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
