/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.assignment1;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Then Wei Cheng
 */
public class Feedback extends javax.swing.JFrame {
    private User user;
    private Appointment appointment;
    /**
     * Creates new form Student_Feedback
     */
    public Feedback(User user) {
        this.user = user;
        this.appointment = appointment;
        initComponents();
        loadAppointmentsFromFile("past");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        appointmentTable = new javax.swing.JTable();
        provideFeedback = new javax.swing.JButton();
        viewFeedback = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jLabel1.setText("Feedback");

        appointmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        // Add TableRowSorter for sorting functionality
        DefaultTableModel model = (DefaultTableModel) appointmentTable.getModel();
        javax.swing.table.TableRowSorter<DefaultTableModel> sorter = new javax.swing.table.TableRowSorter<>(model);
        appointmentTable.setRowSorter(sorter);
        jScrollPane1.setViewportView(appointmentTable);

        provideFeedback.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        provideFeedback.setText("Provide Feedback");
        provideFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provideFeedbackActionPerformed(evt);
            }
        });

        viewFeedback.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        viewFeedback.setText("View Feedback");
        viewFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFeedbackActionPerformed(evt);
            }
        });

        backbutton.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        backbutton.setText("Back");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(464, 464, 464)
                .addComponent(jLabel1)
                .addContainerGap(472, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backbutton)
                .addGap(157, 157, 157)
                .addComponent(provideFeedback)
                .addGap(126, 126, 126)
                .addComponent(viewFeedback)
                .addGap(176, 176, 176))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(provideFeedback)
                    .addComponent(viewFeedback)
                    .addComponent(backbutton))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadAppointmentsFromFile(String filterType) {
        DefaultTableModel model = (DefaultTableModel) appointmentTable.getModel();
    model.setRowCount(0); // Clear the table before loading new data
    String[] colHeadings = {"AppointmentID","StudentsID","Username","SlotsID", "LectureID", "Username","TimeSlots", "Date", "Booked On", "Status", "Notes"};
    model.setColumnIdentifiers(colHeadings); // Set column headers

    LocalDate today = LocalDate.now(); // Get today's date
    
    try (BufferedReader br = new BufferedReader(new FileReader("appointment.txt"))) {
        String line;
        while ((line = br.readLine()) != null) {
            String[] row = line.split(",");
            if (row.length < 8) continue; // Skip incomplete lines

            // Ensure that we filter only by the current user and the correct appointment type (student or lecturer)
            if (row[1].equals(user.getUserID()) || row[4].equals(user.getUserID())) {
                
                // Get the status from the 10th column (index 9)
                String status = row[9];

                // Skip appointments with status "Rejected"
                if ("Rejected".equals(status)) {
                    continue; // Skip this iteration and don't add the row to the table
                }

                try {
                    LocalDate bookingDate = LocalDate.parse(row[7], DateTimeFormatter.ofPattern("dd/MM/yyyy"));
                    if (filterType.equals("past") && bookingDate.isBefore(today)) {
                        model.addRow(row); // Add row to table if it's a past appointment and not rejected
                    }
                } catch (DateTimeParseException e) {
                    System.err.println("Invalid date: " + row[7]);
                }
            }
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error loading appointments: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }
    
    private void viewFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewFeedbackActionPerformed
        int selectedRow = appointmentTable.getSelectedRow(); // Get the selected row index
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select an appointment to view feedback.", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        DefaultTableModel model = (DefaultTableModel) appointmentTable.getModel();
        String appointmentID = model.getValueAt(selectedRow, 0).toString();
        try (BufferedReader br = new BufferedReader(new FileReader("appointment.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] columns = line.split(",");
                if (columns[0].equals(appointmentID)) {
                    String studentFeedback = (columns.length > 11 && !columns[11].equals("None")) ? columns[11] : "No feedback provided";
                    for (int i = 0; i < columns.length; i++) {
                    columns[i] = columns[i].replace('@', ',');
                        }
                    String studentRating = (columns.length > 12 && !columns[12].equals("None")) ? columns[12] : "No rating provided";
                    String lecturerFeedback = (columns.length > 13 && !columns[13].equals("None")) ? columns[13] : "No feedback provided";
                    for (int i = 0; i < columns.length; i++) {
                    columns[i] = columns[i].replace('@', ',');
                        }
                    String lecturerRating = (columns.length > 14 && !columns[14].equals("None")) ? columns[14] : "No rating provided";
                    
                    //pass the details to feedback page and show the feedback page.
                    new ViewFeedback(user,appointmentID, studentFeedback, studentRating, lecturerFeedback, lecturerRating).setVisible(true);
                    return;
                }
            }
            JOptionPane.showMessageDialog(this, "No feedback found for the selected appointment.", "No Feedback", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error reading feedback data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_viewFeedbackActionPerformed

    private void provideFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provideFeedbackActionPerformed
        int selectedRow = appointmentTable.getSelectedRow(); // Get selected row index

            // Check if no row is selected
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(this, "Please select an appointment to provide feedback.", "No Selection", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Get appointment ID from the table model
            DefaultTableModel model = (DefaultTableModel) appointmentTable.getModel();
            String appointmentID = model.getValueAt(selectedRow, 0).toString(); // Assuming first column is Appointment ID

            // Open the feedback window
            new Provide_Feedback(user, appointmentID).setVisible(true);
    }//GEN-LAST:event_provideFeedbackActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // Check the role of the user and navigate accordingly
        if (user.getRole().equals("Student")) {
            // If the role is student, go to Student_features page
            Student_features Sf = new Student_features(user);
            Sf.setVisible(true);
        } else if (user.getRole().equals("Lecturer")) {
            // If the role is lecturer, go to Lecturer_features page
            Lecturer_features Lf = new Lecturer_features(user);
            Lf.setVisible(true);
        }
        // Close the current frame
        this.dispose();
    }//GEN-LAST:event_backbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                User user = new User(null, null, null, null, null);
                new Feedback(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable appointmentTable;
    private javax.swing.JButton backbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton provideFeedback;
    private javax.swing.JButton viewFeedback;
    // End of variables declaration//GEN-END:variables
}
