/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.assignment1;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Then Wei Cheng
 */
public class LecturerViewAppointment extends javax.swing.JFrame {
    private User user;

    /**
     * Creates new form LecturerViewAppointment
     */
    public LecturerViewAppointment(User user) {
        this.user = user;
        initComponents();
        //this code actually should change inside the private voic initComponents()
        /*appointmentTable.setModel(new DefaultTableModel(
            new Object[][] {},
            new String[] {}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Disable editing for all cells
            }
        });
        jScrollPane1.setViewportView(appointmentTable);*/
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        appointmentTable = new javax.swing.JTable();
        viewUpcomingBtn = new javax.swing.JButton();
        viewPastBtn = new javax.swing.JButton();
        viewAllBtn = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jLabel1.setText("View Appointments");

        appointmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {}
        ){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        });
        // Add TableRowSorter for sorting functionality
        DefaultTableModel model = (DefaultTableModel) appointmentTable.getModel();
        javax.swing.table.TableRowSorter<DefaultTableModel> sorter = new javax.swing.table.TableRowSorter<>(model);
        appointmentTable.setRowSorter(sorter);
        jScrollPane1.setViewportView(appointmentTable);

        viewUpcomingBtn.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        viewUpcomingBtn.setText("View Upcoming");
        viewUpcomingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUpcomingBtnActionPerformed(evt);
            }
        });

        viewPastBtn.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        viewPastBtn.setText("View Past");
        viewPastBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPastBtnActionPerformed(evt);
            }
        });

        viewAllBtn.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        viewAllBtn.setText("View All");
        viewAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllBtnActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(442, 442, 442)
                .addComponent(jLabel1)
                .addContainerGap(491, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(140, 140, 140)
                .addComponent(viewUpcomingBtn)
                .addGap(142, 142, 142)
                .addComponent(viewPastBtn)
                .addGap(130, 130, 130)
                .addComponent(viewAllBtn)
                .addGap(175, 175, 175))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewUpcomingBtn)
                    .addComponent(viewPastBtn)
                    .addComponent(viewAllBtn)
                    .addComponent(backButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewUpcomingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewUpcomingBtnActionPerformed
        loadAppointmentsFromFile("upcoming");
    }//GEN-LAST:event_viewUpcomingBtnActionPerformed

    private void viewPastBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPastBtnActionPerformed
        loadAppointmentsFromFile("past");
    }//GEN-LAST:event_viewPastBtnActionPerformed

    private void viewAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllBtnActionPerformed
        loadAppointmentsFromFile("all");
    }//GEN-LAST:event_viewAllBtnActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        Lecturer_features Lf = new Lecturer_features(user);
        Lf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void loadAppointmentsFromFile(String filterType) {
        DefaultTableModel model = (DefaultTableModel) appointmentTable.getModel();
        model.setRowCount(0); // Clear the table before loading new data
        String[] colHeadings = {"AppointmentID","StudentsID","Username","SlotsID", "LectureID", "Username","TimeSlots", "Date", "Booked On", "Status", "Notes"};
        model.setColumnIdentifiers(colHeadings); // Set column headers

        LocalDate today = LocalDate.now(); // Get today's date
        
        try (BufferedReader br = new BufferedReader(new FileReader("appointment.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] row = line.split(",");
                if (row[4].equals(user.getUserID())) { // Check if appointment belongs to the lecturer
                    // Parse the booking date from the file
                    LocalDate bookingDate = LocalDate.parse(row[7], DateTimeFormatter.ofPattern("dd/MM/yyyy"));
                
                   
                    // Filter based on the filterType
                    if (filterType.equals("all") || 
                        (filterType.equals("upcoming") && bookingDate.isAfter(today)) || 
                        (filterType.equals("past") && bookingDate.isBefore(today))) {
                        model.addRow(row);
                    }
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error loading appointments: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Error parsing appointment date: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LecturerViewAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LecturerViewAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LecturerViewAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LecturerViewAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                User user = new User(null, null, null, null, null);
                new LecturerViewAppointment(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable appointmentTable;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewAllBtn;
    private javax.swing.JButton viewPastBtn;
    private javax.swing.JButton viewUpcomingBtn;
    // End of variables declaration//GEN-END:variables
}
