/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.assignment1;

import javax.swing.JOptionPane;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
/**
 *
 * @author Then Wei Cheng
 */
public class Register_form extends BaseForm{
    private static final String DELIMITER = ",";

    /**
     * Creates new form Register_form
     */
    public Register_form() {
        initComponents();
    }
    
    @Override
    public void initializeComponents(){
        initComponents();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JTTpNum = new javax.swing.JTextField();
        JTName = new javax.swing.JTextField();
        JTEmail = new javax.swing.JTextField();
        RegisterBtn = new javax.swing.JButton();
        ResetBtn = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JTPass = new javax.swing.JPasswordField();
        jCheckBox = new javax.swing.JCheckBox();
        loginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setText(" Register Form");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 30, 170, -1));

        jLabel1.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 81, -1, -1));

        jLabel3.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel3.setText("Name :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 60, -1));

        jLabel4.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel4.setText("Password :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel5.setText("Email :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 80, -1));

        JTTpNum.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        JTTpNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTTpNumActionPerformed(evt);
            }
        });
        getContentPane().add(JTTpNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 190, 30));

        JTName.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        getContentPane().add(JTName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 190, -1));

        JTEmail.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        getContentPane().add(JTEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 190, 30));

        RegisterBtn.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        RegisterBtn.setText("Register");
        RegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBtnActionPerformed(evt);
            }
        });
        getContentPane().add(RegisterBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, -1, -1));

        ResetBtn.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        ResetBtn.setText("Reset");
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ResetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lecturer", "Student" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 190, 30));

        jLabel6.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel6.setText("Role :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel7.setText("User ID :");
        jLabel7.setMaximumSize(new java.awt.Dimension(50, 20));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, 30));

        JTPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTPassActionPerformed(evt);
            }
        });
        getContentPane().add(JTPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 190, 30));

        jCheckBox.setText("Show Password");
        jCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        loginButton.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBtnActionPerformed
    File userFile = new File("user_data.txt");
    if (!userFile.exists()) {
        try {
            // Try creating the file if it doesn't exist
            boolean fileCreated = userFile.createNewFile();
            if (fileCreated) {
                System.out.println("User data file created successfully.");
            }
        } catch (IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "An error occurred while creating the file: " + e.getMessage(), "File Creation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }
        // Validate input
        if (JTTpNum.getText().equals("")) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please fill out your TP number");
            return;
        }
        if (JTName.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill out Name");
            return;
        }
        if (JTPass.getText().equals("")) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please fill out password");
            return;
        }
        if (JTEmail.getText().equals("")) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please fill out Email");
            return;
        }

        // Check if role is Student and User ID contains "tp"
        if (jComboBox1.getSelectedItem().equals("Student") && !JTTpNum.getText().toLowerCase().contains("tp")) {
            JOptionPane.showMessageDialog(this, "Student User ID must include 'tp'.", "Invalid User ID", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Check if role is Student and User ID contains "tp"
        if (jComboBox1.getSelectedItem().equals("Lecturer") && !JTTpNum.getText().toLowerCase().contains("lc")) {
            JOptionPane.showMessageDialog(this, "Lceture User ID must include 'lc'.", "Invalid User ID", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Create User object
        User newUser = new User(JTTpNum.getText().trim(), JTName.getText().trim(), JTPass.getText().trim(), JTEmail.getText().trim(), (String)jComboBox1.getSelectedItem());

        // Validate password
        Register_CheckPassword passwordChecker = new Register_CheckPassword();
        if (!passwordChecker.checkPasswordRule(newUser.getPassword())) {
            javax.swing.JOptionPane.showMessageDialog(this, "Password must be at least 8 characters long and contain at least 3 of the following:"
                    + " a number, a lowercase letter, an uppercase letter, and a special symbol.");
            return;
        }
        
        // Validate email
        if (!Register_CheckEmail.isEmail(newUser.getEmail())) {
            JOptionPane.showMessageDialog(this, "Invalid email format. Please enter a valid email address.", "Email Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        //check for duplicates
        if (isRegistered(newUser)) {
            JOptionPane.showMessageDialog(this, "An account with this TP Number or Email is already registered.", "Registration Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        saveUsersDatas(newUser);
}

    // Check if user is already registered
    private boolean isRegistered (User user){
        try (BufferedReader br = new BufferedReader(new FileReader("user_data.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                // Split the line into user data using the delimiter
                String[] userData = line.split(",");
                if (userData.length >= 4) { // Ensure line has the expected number of fields
                    String existingUserID = userData[0]; // TP Number is the first field
                    String existingEmail = userData[3];    // Email is the fourth field

                    // Check for duplicate TP Number or Email
                    if (existingUserID.equals(user.getUserID()) || existingEmail.equals(user.getEmail())) {
                        return true;
                    }
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "An error occurred while reading data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }

        // Save user data in the specified format
    private void saveUsersDatas(User user){
        String role = (String) jComboBox1.getSelectedItem();
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("user_data.txt", true))) {
            String formattedData = user.getUserID() + DELIMITER 
                                 + user.getName() + DELIMITER
                                 + user.getPassword() + DELIMITER 
                                 + user.getEmail() + DELIMITER 
                                 + user.getRole(); // Append role
            writer.write(formattedData);
            writer.newLine(); // Move to the next line
            javax.swing.JOptionPane.showMessageDialog(this, "Registration Successful!");
            User_Login_form ULf = new User_Login_form();

            //Direct to the login form after register button is clicked
            if (role.equals("Student")) {
                ULf.setVisible(true);
                this.dispose();
            } else if (role.equals("Lecturer")) {
                ULf.setVisible(true);
                this.dispose();
            }
            
        } catch (IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "An error occurred while saving data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_RegisterBtnActionPerformed

    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
        JTTpNum.setText("");
        JTName.setText("");
        JTPass.setText("");
        JTEmail.setText("");
    }//GEN-LAST:event_ResetBtnActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
  
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void JTTpNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTTpNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTTpNumActionPerformed

    private void JTPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTPassActionPerformed

    private void jCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxActionPerformed
        if (jCheckBox.isSelected()) {
            // Show password
            JTPass.setEchoChar((char) 0); // Remove echo char to show plain text
        } else {
            // Hide password
            JTPass.setEchoChar('\u2022'); // Set echo char back to bullet symbol
        }
    }//GEN-LAST:event_jCheckBoxActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        User_Login_form ULf = new User_Login_form();
        ULf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTEmail;
    private javax.swing.JTextField JTName;
    private javax.swing.JPasswordField JTPass;
    private javax.swing.JTextField JTTpNum;
    private javax.swing.JButton RegisterBtn;
    private javax.swing.JButton ResetBtn;
    private javax.swing.JCheckBox jCheckBox;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton loginButton;
    // End of variables declaration//GEN-END:variables
}
