/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.assignment1;

import javax.swing.table.DefaultTableModel;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author Then Wei Cheng
 */
public class StudentViewAppointment extends javax.swing.JFrame {
    private User user;
    /**
     * Creates new form ViewAppointment
     */
    public StudentViewAppointment(User user) {
        this.user = user;
        initComponents();
        //this code actually should change inside the private voic initComponents()
        //this code will help to make the table content unchangeble 
        /*appointmentTable.setModel(new DefaultTableModel(
            new Object[][] {},
            new String[] {}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Disable editing for all cells
            }
        });
        jScrollPane1.setViewportView(appointmentTable);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        viewUpcomingBtn = new javax.swing.JButton();
        viewPastBtn = new javax.swing.JButton();
        viewAllBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        appointmentTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jLabel1.setText("View Appointments");

        viewUpcomingBtn.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        viewUpcomingBtn.setText("View Upcoming");
        viewUpcomingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUpcomingBtnActionPerformed(evt);
            }
        });

        viewPastBtn.setFont(new java.awt.Font("Serif", 2, 14)); // NOI18N
        viewPastBtn.setText("View Past");
        viewPastBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPastBtnActionPerformed(evt);
            }
        });

        viewAllBtn.setFont(new java.awt.Font("Serif", 2, 14)); // NOI18N
        viewAllBtn.setText("View All");
        viewAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllBtnActionPerformed(evt);
            }
        });

        BackBtn.setFont(new java.awt.Font("Serif", 2, 14)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        appointmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {}
        ){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        });
        jScrollPane2.setViewportView(appointmentTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(231, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(viewUpcomingBtn)
                        .addGap(138, 138, 138)
                        .addComponent(viewPastBtn)
                        .addGap(75, 75, 75)
                        .addComponent(viewAllBtn)
                        .addGap(228, 228, 228))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(427, 427, 427))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewAllBtn)
                    .addComponent(viewPastBtn)
                    .addComponent(viewUpcomingBtn)
                    .addComponent(BackBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewUpcomingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewUpcomingBtnActionPerformed
        loadAppointmentsFromFile("upcoming");
    }//GEN-LAST:event_viewUpcomingBtnActionPerformed

    private void viewPastBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPastBtnActionPerformed
        loadAppointmentsFromFile("past");
    }//GEN-LAST:event_viewPastBtnActionPerformed

    private void viewAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllBtnActionPerformed
        loadAppointmentsFromFile("all");
    }//GEN-LAST:event_viewAllBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        Student_features Sf = new Student_features(user);
        Sf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void loadAppointmentsFromFile(String filterType) {
        DefaultTableModel model = (DefaultTableModel) appointmentTable.getModel();
        model.setRowCount(0); // Clear the table before loading new data
        String[] colHeadings = {"AppointmentID","StudentsID","Username","SlotsID", "LectureID", "Username","TimeSlots", "Date", "Booked On", "Status", "Notes"};
        model.setColumnIdentifiers(colHeadings); // Set column headers

        LocalDate today = LocalDate.now(); // Get today's date
        
        try (BufferedReader br = new BufferedReader(new FileReader("appointment.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] row = line.split(",");
                if (row[1].trim().equals(user.getUserID().trim())) { // Check if appointment belongs to the student
                    // Parse the booking date from the file
                    LocalDate bookingDate = LocalDate.parse(row[7], DateTimeFormatter.ofPattern("dd/MM/yyyy"));
                
                   
                    // Filter based on the filterType
                    if (filterType.equals("all") || 
                        (filterType.equals("upcoming") && bookingDate.isAfter(today)) || 
                        (filterType.equals("past") && bookingDate.isBefore(today))) {
                        model.addRow(row);
                    }
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error loading appointments: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Error parsing appointment date: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentViewAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentViewAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentViewAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentViewAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                User user = new User(null, null, null, null, null);
                new StudentViewAppointment(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JTable appointmentTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton viewAllBtn;
    private javax.swing.JButton viewPastBtn;
    private javax.swing.JButton viewUpcomingBtn;
    // End of variables declaration//GEN-END:variables
}
